version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: mix phx.server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: app
    env_file: .env
    depends_on:
      - pgsql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4GB'
    restart: always
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    networks:
      - app-network

  pgsql:
    image: postgres:14.4-alpine
    container_name: pgsql
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qapp_dev
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2GB'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local